Enhancement#01 - Change number of products added to cart
rihan-a/JS-rihan-Ecommerce pull request #7
Opened 2022-09-02 13:04 UTC by rihan-a

## Description
An upgrade to the user experience, aiming at the ease of use 
Users can choose how many products they would like to add to cart from both Home page & Shop page

## Screenshots
<img width="1440" alt="Screenshot 2022-09-02 at 14 58 05" src="https://user-images.githubusercontent.com/90706137/188150963-a925b097-0d27-4513-a937-e578dc18ae80.png">

## Testing
1- Open website Home page or Shop page
2- Go to a product
3- Press (+) to add product to cart and (-) to remove product from cart
4- Go to to cart page to make sure the added products are there 
4- Cart count should be updated in all pages

2022-09-02 21:21 UTC, SabryShawally requested changes
Overall a good start! Please find some comments I added since I didn’t do a full review. Please focus on readability and consistency in your coding style as it would help me as a reader and you later if you want to make changes later in time

2022-09-02 21:21 UTC, SabryShawally commented on assets/css/style.css
> +.pro-minus,
What does ‘pro-‘ stand for? I find it difficult to know what it references/means just by reading.

2022-09-02 21:21 UTC, SabryShawally commented on assets/css/style.css
> +  .pro-minus,
Similarly here

2022-09-02 21:21 UTC, SabryShawally commented on assets/css/style.css
> +/* ---------- Featured products ----------  / -------------- Shop Page --------------------- */
Why not separate to different css files for each page? This way you minimize the data that needs to be transferred for each page and only load what you need for the page displayed

2022-09-02 21:21 UTC, SabryShawally commented on assets/css/style.css
> -#product1 .pro .desc h4:hover {
What is product 1? That is difficult to understand what it means

2022-09-02 21:21 UTC, SabryShawally commented on assets/css/style.css
> +  }
Please add proper spacing between the styles

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/cart.js
> +  cartCount2.innerHTML = `Cart(0)`;
What is cartCount2 ? Please use meaningful names

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/fetchProducts.js
> +export async function saveProductsToLocal() {
The name of the file doesn’t seem to match what this function does. I expect it to only do read only changes from the words fetchProducts. But this method also saves to local store

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/fetchProducts.js
> +    localStorage.setItem("allProducts", JSON.stringify(modifiedProductsList));
Why not just save it as a json object?

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/global.js
>  function showHideMenu() {
The name is confusing I would suggest toggleMenu

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/home.js
> +saveProductsToLocal();
This says save, but it then does print? I would also expect it to take an argument of what it’s meant to save

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/home.js
> +  // else {
Please remove unused code

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/home.js
> +    localStorage.setItem("productID", id);
Should you not save before redirecting?

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/home.js
> +// Touch event for + / - styling
ditto

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/newCart.js
> +import { changeNumberOfUnits } from "./changeNumber.js";
What is newCart? The name of the file should be updated

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/newCart.js
> +let cartCount2 = document.querySelector(".cart-btn2");
CartCount2 doesn’t make any sense

2022-09-02 21:21 UTC, SabryShawally commented on assets/scripts/newCart.js
> +let cartCount2 = document.querySelector(".cart-btn2");
This file seems to be a duplicate of cart.js

2022-09-11 19:42 UTC, rihan-a commented on assets/scripts/home.js
> +  // else {
fixed

2022-09-18 10:08 UTC, rihan-a commented on assets/css/style.css
> +.pro-minus,
Pro stand for product

2022-09-18 10:09 UTC, rihan-a commented on assets/css/style.css
> +/* ---------- Featured products ----------  / -------------- Shop Page --------------------- */
This is a good idea, I will split them and commit.

2022-10-26 16:30 UTC, SabryShawally approved these changes
LGTM approving for now

2022-10-26 16:32 UTC, merged